//HintName: Sample_InvoiceDoc_ParchmentTemplate.g.cs
// <auto-generated />
#nullable enable
namespace Sample;

partial class InvoiceDoc
{
    public static string TemplatePath => "invoice.docx";
    public static string TemplateName => "InvoiceDoc";

    public static void RegisterWith(global::Parchment.TemplateStore store, string? basePath = null)
    {
        var path = basePath is null ? TemplatePath : global::System.IO.Path.Combine(basePath, TemplatePath);
        var bytes = global::System.IO.File.ReadAllBytes(path);
        store.RegisterDocxTemplate<global::Sample.Invoice>(TemplateName, bytes);
    }
}
