//HintName: Sample_BadLoop_ParchmentTemplate.g.cs
// <auto-generated />
#nullable enable
namespace Sample;
partial class BadLoop
{
    public static string TemplatePath => "template.docx";
    public static string TemplateName => "BadLoop";

    public static void RegisterWith(global::Parchment.TemplateStore store, string? basePath = null)
    {
        var path = basePath is null ? TemplatePath : global::System.IO.Path.Combine(basePath, TemplatePath);
        store.RegisterDocxTemplate<global::Sample.Letter>(TemplateName, path);
    }
}
