//HintName: Sample_StringLoop_ParchmentTemplate.g.cs
// <auto-generated />
#nullable enable
namespace Sample;

partial class StringLoop
{
    public static string TemplatePath => "template.docx";
    public static string TemplateName => "StringLoop";

    public static void RegisterWith(global::Parchment.TemplateStore store, string? basePath = null)
    {
        var path = basePath is null ? TemplatePath : global::System.IO.Path.Combine(basePath, TemplatePath);
        var bytes = global::System.IO.File.ReadAllBytes(path);
        store.RegisterDocxTemplate<global::Sample.Letter>(TemplateName, bytes);
    }
}
