//HintName: Sample_InvoiceMd_ParchmentTemplate.g.cs
// <auto-generated />
#nullable enable
namespace Sample;
partial class InvoiceMd
{
    public static string TemplatePath => "template.md";
    public static string TemplateName => "InvoiceMd";

    public static void RegisterWith(global::Parchment.TemplateStore store, string? basePath = null, global::System.IO.Stream? styleSource = null)
    {
        var path = basePath is null ? TemplatePath : global::System.IO.Path.Combine(basePath, TemplatePath);
        var markdown = global::System.IO.File.ReadAllText(path);
        store.RegisterMarkdownTemplate<global::Sample.Invoice>(TemplateName, markdown, styleSource);
    }
}
