//HintName: Sample_OuterRecord_LetterModel_ParchmentModel.g.cs
// <auto-generated />
#nullable enable
namespace Sample;
partial record OuterRecord
{
  partial class LetterModel
  {
    public static string TemplatePath => "template.docx";
    public static string TemplateName => "LetterModel";

    static readonly global::System.Collections.Generic.KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_OuterRecord_LetterModel =
    {
      new("Customer", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.OuterRecord.LetterModel)o).Customer)),
    };

    static readonly global::System.Collections.Generic.KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Customer =
    {
      new("Name", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Customer)o).Name)),
    };

    public static void RegisterWith(global::Parchment.TemplateStore store, string? basePath = null)
    {
      global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.OuterRecord.LetterModel), _Accessors_global__Sample_OuterRecord_LetterModel);
      global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Customer), _Accessors_global__Sample_Customer);
      var path = basePath is null ? TemplatePath : global::System.IO.Path.Combine(basePath, TemplatePath);
      store.RegisterDocxTemplate<global::Sample.OuterRecord.LetterModel>(TemplateName, path);
    }
  }
}
