//HintName: Sample_Letter_ParchmentModel.g.cs
// <auto-generated />
#nullable enable

using System.Collections.Generic;
namespace Sample;
partial class Letter
{
  public static string TemplatePath => "letter.docx";
  public static string TemplateName => "Letter";

  static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Letter =
  {
    new("Customer", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Letter)o).Customer)),
  };
  static readonly KeyValuePair<string, global::Fluid.IMemberAccessor>[] _Accessors_global__Sample_Customer =
  {
    new("Name", new global::Fluid.Accessors.DelegateAccessor((o, _) => ((global::Sample.Customer)o).Name)),
  };

  public static void RegisterWith(global::Parchment.TemplateStore store, string? basePath = null)
  {
    global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Letter), _Accessors_global__Sample_Letter);
    global::Parchment.Generated.GeneratedRegistration.RegisterFluidAccessors(typeof(global::Sample.Customer), _Accessors_global__Sample_Customer);
    var path = basePath is null ? TemplatePath : global::System.IO.Path.Combine(basePath, TemplatePath);
    store.RegisterDocxTemplate<global::Sample.Letter>(TemplateName, path);
  }
}
