//HintName: Sample_InvoiceDoc_ParchmentTemplate.g.cs
// <auto-generated />
#nullable enable
namespace Sample;
partial class InvoiceDoc
{
    public static string TemplatePath => "template.docx";
    public static string TemplateName => "InvoiceDoc";

    public static void RegisterWith(global::Parchment.TemplateStore store, string? basePath = null)
    {
        var path = basePath is null ? TemplatePath : global::System.IO.Path.Combine(basePath, TemplatePath);
        store.RegisterDocxTemplate<global::Sample.Invoice>(TemplateName, path);
    }
}
